# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 00:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0003_invitation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_players', models.IntegerField(help_text='2-8 players', validators=[django.core.validators.MinValueValidator(2, message='Must have at least 2 players'), django.core.validators.MaxValueValidator(8, message='Cannot have more than 8 players')], verbose_name='Number of Players')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.CharField(blank=True, max_length=300)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='message',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='game',
            name='host',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('F', 'Finished'), ('C', 'Cancelled')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='to_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='setup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Setup'),
        ),
    ]
