# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_hand'),
        ('game', '0007_player_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='hand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.Hand'),
        ),
    ]
