# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20160801_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.IntegerField(blank=True, default=-1),
            preserve_default=False,
        ),
    ]
