# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_player_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.IntegerField(),
        ),
    ]
