# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_game_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='turn',
            field=models.BooleanField(default=False),
        ),
    ]
