# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20160802_0815'),
        ('game', '0015_player_turn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face_up', models.BooleanField(default=True)),
                ('cards', models.ManyToManyField(null=True, to='cards.Card')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.Action'),
        ),
    ]
