# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0022_auto_20160804_0343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='error',
        ),
        migrations.AddField(
            model_name='player',
            name='error',
            field=models.CharField(default='', max_length=100),
        ),
    ]
