# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_player_face_up'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='round_end',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='player',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
