# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20160805_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='order',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
