# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_game_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='round_end',
        ),
        migrations.RemoveField(
            model_name='game',
            name='title',
        ),
    ]
