# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-01 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_remove_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hand',
            name='cards',
            field=models.ManyToManyField(to='cards.Card'),
        ),
    ]
