# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_player_turn'),
        ('cards', '0009_auto_20160801_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cards', models.ManyToManyField(to='cards.Card')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.Player')),
            ],
        ),
    ]
