# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selected',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='selected',
            name='player',
        ),
        migrations.AddField(
            model_name='hand',
            name='selected',
            field=models.ManyToManyField(related_name='selected', to='cards.Card'),
        ),
        migrations.AlterField(
            model_name='hand',
            name='cards',
            field=models.ManyToManyField(related_name='cards', to='cards.Card'),
        ),
        migrations.DeleteModel(
            name='Selected',
        ),
    ]
